securisation with NFTables.

diff --git a/TVConnections/Singularity/script_icewm b/TVConnections/Singularity/script_icewm
--- a/TVConnections/Singularity/script_icewm
+++ b/TVConnections/Singularity/script_icewm
@@ -65,8 +65,7 @@ export STARTUP=/tmp/startup_$DATE
 echo "#!/bin/bash 
 
 sleep 1
-
-xterm -rv -geometry ${RESOL}-0-0 -e /opt/TiledViz/client_python ${SINGULARITYID} ${myPORT} ${myFront} &
+xterm -rv -geometry ${RESOL}-0-0 -e bash -c \"/opt/TiledViz/client_python ${SINGULARITYID} ${myPORT} ${myFront} 2>&1 > /tmp/out_client \" &
 
 sleep 1
 icewm
@@ -76,6 +75,7 @@ icewm
 " >${STARTUP}
 chmod 755 ${STARTUP}
 
+#set -vx
 export LC_ALL=C
 
 export LOGxvfb=/tmp/out_xvfb_$DATE
@@ -96,7 +96,7 @@ echo $XVFBCOMMAND > ${LOGxvfb}
 OUTpgrepX=""
 loopCount=0
 timeout=10
-set -vx
+#set -vx
 until [ X"$OUTpgrepX" != X"" ];
 do
     $XVFBCOMMAND &
@@ -105,11 +105,17 @@ do
     # $XVFBRCOMMAND &
     sleep 2
 
-    OUTpgrepX=$(pgrep -fa Xvfb)
-    echo $OUTpgrepX >> ${LOGxvfb}
+    OUTpgrepX=$(pgrep -fa "Xvfb :$myXPort")
+    echo "OUTpgrepX: $OUTpgrepX" >> ${LOGxvfb}
 
     if [ X"$OUTpgrepX" != X"" ]; then
-	${STARTUP} 2>&1 & >>${LOGxvfb}
+	${STARTUP} 2>&1 >>${LOGxvfb}
+    fi
+    sleep 5
+    
+    OUTstartup=$(pgrep -fa "^icewm")
+    echo "OUTstartup: $OUTstartup" >> ${LOGxvfb}
+    if [ X"$OUTstartup" != X"" ]; then
 	break
     fi
 
@@ -122,7 +128,7 @@ do
     fi
 
 done
-set +vx
+#set +vx
 
 # Set defaults if the user did not specify envs.
 screen=${XVFB_SCREEN:-0}
@@ -136,17 +142,17 @@ echo $DISPLAY
 
 #Xvfb ${DISPLAY} -screen ${screen} ${resolution} &
 
-loopCount=0
-until xdpyinfo -display ${DISPLAY} > /dev/null 2>&1
-do
-    loopCount=$((loopCount+1))
-    sleep 1
-    if [ ${loopCount} -gt ${timeout} ]
-    then
-        echo "xvfb failed to start"
-        exit 1
-    fi
-done
+# loopCount=0
+# until xdpyinfo -display ${DISPLAY} > /dev/null 2>&1
+# do
+#     loopCount=$((loopCount+1))
+#     sleep 1
+#     if [ ${loopCount} -gt ${timeout} ]
+#     then
+#         echo "xvfb failed to start"
+#         exit 1
+#     fi
+# done
 
 cat  ${LOGxvfb} >> $LOGFILE
 echo "Log file is $LOGFILE $(date +%F_%H-%M-%S)" >> $LOGFILE
